#!/bin/bash
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SIMPLE EXAMPLE (abs) ***"
echo "Press <enter> to load modules:"
read junk
./ldmod
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
